[build]
  command = "yarn build"
  publish="build"
  base = ""


  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build.environment]
  NODE_VERSION = "10.11.0"
  YARN_VERSION = "1.19.0"
  NPM_VERSION = "6.12.0"